#pragma once

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by extract_textures.py

#include <cstdint>

namespace MCPP {

enum class BlockID : uint8_t {
    Air = 0,
    Stone = 1,
    Dirt = 2,
    Grass = 3,
    Cobblestone = 4,
    OakPlanks = 5,
    OakLog = 6,
    OakLeaves = 7,
    Sand = 8,
    Gravel = 9,
    GoldOre = 10,
    IronOre = 11,
    CoalOre = 12,
    DiamondOre = 13,
    Bedrock = 14,
    Water = 15,
    Lava = 16,
    Glass = 17,
    Sandstone = 18,
    Brick = 19,
    TNT = 20,
    MossyCobblestone = 21,
    Obsidian = 22,
    CraftingTable = 23,
    Furnace = 24,
    Snow = 25,
    Ice = 26,
    Clay = 27,
    Netherrack = 28,
    SoulSand = 29,
    Glowstone = 30,
    StoneBricks = 31,
    MossyStoneBricks = 32,
    CrackedStoneBricks = 33,
    Deepslate = 34,
    DeepslateCoalOre = 35,
    DeepslateIronOre = 36,
    DeepslateDiamondOre = 37,
    Diorite = 38,
    Granite = 39,
    Andesite = 40,
    COUNT = 41
};

constexpr uint32_t BLOCK_COUNT = 41;

} // namespace MCPP
